[package]
name = "deser-stringified"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive", "std", "alloc"] }
serde_json = { version = "1.0.140", features = ["std", "alloc"] }
serde_yaml = "0.9.34"
